# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            'deepthinker'
tagline:          'deepthinker tag line'
description:      'deepthinker <b>programmer</b>, <a href="https://thedeepthinker.github.io/Write/">thinker</a>'
url:              https://github.com/TheDeepThinker/Write
baseurl:          /

author:
  name:           'deepthinker'
  url:            https://github.com/TheDeepThinker

paginate:         5

# Custom vars
version:          0.0.1

github:
  repo:           https://github.com/TheDeepThinker/TheDeepThinker.github.io
